name: pet_doption_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.4.1
  flutter_screenutil: ^5.6.1
  build_runner: ^2.4.8
  equatable: ^2.0.5
  get_it: ^7.6.0
  bloc_test: ^9.1.4
  test_cov_console: ^0.2.2
  mocktail: ^1.0.0
  shared_preferences: ^2.2.0
  flutter_native_splash: ^2.3.5
  intl: ^0.18.0
  lottie: ^2.6.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  string_validator: ^1.1.0
  country_code_picker: ^3.0.0
  brasil_fields: ^1.14.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  dartz: ^0.10.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0




flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
